apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: redis01
  name: redis01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis01
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: redis01
    spec:
      containers:
        - image: redis:3
          name: redis01
          resources: {}
      restartPolicy: Always
status: {}
