apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: results-app
  name: results-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: results-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: results-app
    spec:
      containers:
        - image: devunix/results-app
          name: results-app
          resources: {}
      restartPolicy: Always
status: {}
