apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: store
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: store
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: store
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: pg8675309
            - name: POSTGRES_USER
              value: postgres
          image: postgres:9.5
          name: store
          resources: {}
      restartPolicy: Always
status: {}
