apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vote-worker
  name: vote-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vote-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: vote-worker
    spec:
      containers:
        - env:
            - name: FROM_REDIS_HOST
              value: "1"
            - name: TO_REDIS_HOST
              value: "1"
          image: devunix/vote-worker
          name: vote-worker
          resources: {}
      restartPolicy: Always
status: {}
