apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-vote-app
  name: web-vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-vote-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web-vote-app
    spec:
      containers:
        - env:
            - name: WEB_VOTE_NUMBER
              value: "01"
            - name: constraint
              value: node==frontend01
          image: devunix/web-vote-app
          name: web-vote-app
          resources: {}
      restartPolicy: Always
status: {}
